### ISSUE TITLE
timer on blur

### ISSUE THREAD

**Issue by bsitruk** [ivkremer/jquery-simple-combobox#63] opened 2015-03-12 23:03 UTC
Hi,
I don't really understand the need of the timer of 200ms in the blur event. 
It's annoying, cause if I change select' value and then immediatly click on the submit button, the new value won't send (Cause the click event will trigger before the blur timeout end).

Any advice ? 
Thanks for your work.

**Comment by gjsjohnmurray** [comment] 2015-03-12 23:35
I haven't yet tried out the scenario you describe, but I think I see what you mean.

I'm the person who introduced the timer on blur. It landed in pull request #48 from me as a fix for issue #47. I devised it as an alternative solution to a blur issue I'd previously addressed by using the event's relatedTarget property. See issue #25 for the main discussion.

The relatedTarget fix landed in pull #35 which was also meant to fix #32. Only later did I realize that Firefox doesn't yet implement relatedTarget. Hence the timer solution.

I think the goal is to have the blur event on the display field do nothing if it's caused by the user clicking on one of the other elements that make up the scombobox (e.g. to scroll the dropped list). Checking relatedTarget should do the job but (a) Firefox doesn't have it, and (b) it wasn't being reliable for me on Chrome (v40 at the time).

Suggestions are welcome.

**Comment by gjsjohnmurray** [comment] 2015-03-13 01:56
Status update. I'm testing a solution that brings some of the logic back out of the timer event into the blur event, leaving the timer event doing only what must be skipped in certain situations.

**Comment by bsitruk** [comment] 2015-03-13 09:46
Thanks a lot ! 
I'll give you some feedback later :)

**Closed** 2015-03-17 16:33 UTC
